name: Tag

on:
  push:
    branches: [main]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensure that all tags are available

      - name: "Compute next version tag"
        run: |-
          nextVersionTag=$(make print_next_version_tag)
          echo "next: $nextVersionTag"
          echo "::set-output name=next_version_tag::$nextVersionTag"
        id: compute_next_version_tag

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.CODECRAFTERS_BOT_GITHUB_TOKEN }}
          custom_tag: ${{ steps.compute_next_version_tag.outputs.next_version_tag }}
          tag_prefix: ""
