name: Test Dataset

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA to test"
        required: true
      dataset_name:
        description: "Dataset name"
        required: true

# concurrency:
#   group: ${{ inputs.commit_sha }}-${{ inputs.dataset_name }}
#   cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest-16-cores
    timeout-minutes: 30

    services:
      redis:
        image: redis:latest
        ports:
          - 6911:6379

      postgres:
        image: postgres:12.1
        env:
          POSTGRES_PASSWORD: psql_pass
          POSTGRES_USER: psql_user
          POSTGRES_DB: psql_db
        ports:
          - 6912:5432

        # This isn't useful because other steps take long enough...
        # options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commit_sha }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - run: scripts/download_dataset.sh ${{ inputs.dataset_name }}
      - run: git config --global user.email "hello@codecrafters.io"
      - run: git config --global user.name "codecrafters-bot"

      - run: bundle exec rails db:migrate

      - name: Run tests
        run: bundle exec rails runner scripts/validate_dataset.rb tmp/datasets/${{ inputs.dataset_name }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          HELICONE_API_KEY: ${{ secrets.HELICONE_API_KEY }}
          GITHUB_TOKEN: ${{github.token}}

      - name: Persist workflow logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: workflow-logs
          path: tmp/dataset_validations_results

      - name: Summary
        run: |
          echo "# Failure: $(jq -r '.failure' tmp/dataset_validations_results/*/aggregate_results.json)" > $GITHUB_STEP_SUMMARY
          echo "# Success: $(jq -r '.success' tmp/dataset_validations_results/*/aggregate_results.json)" > $GITHUB_STEP_SUMMARY
          echo "# Total: $(jq -r '.total' tmp/dataset_validations_results/*/aggregate_results.json)" > $GITHUB_STEP_SUMMARY
